// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/daemon/proto/search.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	RepoFilter    string                 `protobuf:"bytes,2,opt,name=repo_filter,json=repoFilter,proto3" json:"repo_filter,omitempty"`
	FileFilter    string                 `protobuf:"bytes,3,opt,name=file_filter,json=fileFilter,proto3" json:"file_filter,omitempty"`
	Lang          string                 `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang,omitempty"`
	CaseSensitive bool                   `protobuf:"varint,5,opt,name=case_sensitive,json=caseSensitive,proto3" json:"case_sensitive,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	ContextLines  int32                  `protobuf:"varint,7,opt,name=context_lines,json=contextLines,proto3" json:"context_lines,omitempty"`
	OutputMode    string                 `protobuf:"bytes,8,opt,name=output_mode,json=outputMode,proto3" json:"output_mode,omitempty"`
	RepoNames     map[string]string      `protobuf:"bytes,9,rep,name=repo_names,json=repoNames,proto3" json:"repo_names,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *SearchRequest) GetRepoFilter() string {
	if x != nil {
		return x.RepoFilter
	}
	return ""
}

func (x *SearchRequest) GetFileFilter() string {
	if x != nil {
		return x.FileFilter
	}
	return ""
}

func (x *SearchRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SearchRequest) GetCaseSensitive() bool {
	if x != nil {
		return x.CaseSensitive
	}
	return false
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchRequest) GetContextLines() int32 {
	if x != nil {
		return x.ContextLines
	}
	return 0
}

func (x *SearchRequest) GetOutputMode() string {
	if x != nil {
		return x.OutputMode
	}
	return ""
}

func (x *SearchRequest) GetRepoNames() map[string]string {
	if x != nil {
		return x.RepoNames
	}
	return nil
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Matches       []*Match               `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetMatches() []*Match {
	if x != nil {
		return x.Matches
	}
	return nil
}

type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	RepoPath      string                 `protobuf:"bytes,2,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Line          int32                  `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	Text          string                 `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	Before        string                 `protobuf:"bytes,7,opt,name=before,proto3" json:"before,omitempty"`
	After         string                 `protobuf:"bytes,8,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{2}
}

func (x *Match) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *Match) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *Match) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *Match) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *Match) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *Match) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Match) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *Match) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

type CountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	RepoFilter    string                 `protobuf:"bytes,2,opt,name=repo_filter,json=repoFilter,proto3" json:"repo_filter,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	GroupBy       string                 `protobuf:"bytes,4,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{3}
}

func (x *CountRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *CountRequest) GetRepoFilter() string {
	if x != nil {
		return x.RepoFilter
	}
	return ""
}

func (x *CountRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *CountRequest) GetGroupBy() string {
	if x != nil {
		return x.GroupBy
	}
	return ""
}

type CountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*CountResult         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResponse) Reset() {
	*x = CountResponse{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResponse) ProtoMessage() {}

func (x *CountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResponse.ProtoReflect.Descriptor instead.
func (*CountResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{4}
}

func (x *CountResponse) GetResults() []*CountResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *CountResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CountResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountResult) Reset() {
	*x = CountResult{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountResult) ProtoMessage() {}

func (x *CountResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountResult.ProtoReflect.Descriptor instead.
func (*CountResult) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{5}
}

func (x *CountResult) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *CountResult) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pattern       string                 `protobuf:"bytes,1,opt,name=pattern,proto3" json:"pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Parsed        string                 `protobuf:"bytes,2,opt,name=parsed,proto3" json:"parsed,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Hint          string                 `protobuf:"bytes,4,opt,name=hint,proto3" json:"hint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{7}
}

func (x *ValidateResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateResponse) GetParsed() string {
	if x != nil {
		return x.Parsed
	}
	return ""
}

func (x *ValidateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidateResponse) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type SemanticSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	K             int32                  `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	Repos         []string               `protobuf:"bytes,3,rep,name=repos,proto3" json:"repos,omitempty"`
	Langs         []string               `protobuf:"bytes,4,rep,name=langs,proto3" json:"langs,omitempty"`
	Expand        int32                  `protobuf:"varint,5,opt,name=expand,proto3" json:"expand,omitempty"` // pad lines for snippet; 0 = exact chunk range
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchRequest) Reset() {
	*x = SemanticSearchRequest{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchRequest) ProtoMessage() {}

func (x *SemanticSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchRequest.ProtoReflect.Descriptor instead.
func (*SemanticSearchRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{8}
}

func (x *SemanticSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SemanticSearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SemanticSearchRequest) GetRepos() []string {
	if x != nil {
		return x.Repos
	}
	return nil
}

func (x *SemanticSearchRequest) GetLangs() []string {
	if x != nil {
		return x.Langs
	}
	return nil
}

func (x *SemanticSearchRequest) GetExpand() int32 {
	if x != nil {
		return x.Expand
	}
	return 0
}

type SemanticSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"` // false when the daemon has no semantic index/model loaded
	Hits          []*SemanticHit         `protobuf:"bytes,2,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchResponse) Reset() {
	*x = SemanticSearchResponse{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResponse) ProtoMessage() {}

func (x *SemanticSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResponse.ProtoReflect.Descriptor instead.
func (*SemanticSearchResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{9}
}

func (x *SemanticSearchResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *SemanticSearchResponse) GetHits() []*SemanticHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type SemanticHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Repo          string                 `protobuf:"bytes,1,opt,name=repo,proto3" json:"repo,omitempty"`
	RepoPath      string                 `protobuf:"bytes,2,opt,name=repo_path,json=repoPath,proto3" json:"repo_path,omitempty"`
	File          string                 `protobuf:"bytes,3,opt,name=file,proto3" json:"file,omitempty"`
	Lang          string                 `protobuf:"bytes,4,opt,name=lang,proto3" json:"lang,omitempty"`
	Kind          string                 `protobuf:"bytes,5,opt,name=kind,proto3" json:"kind,omitempty"`
	StartLine     int32                  `protobuf:"varint,6,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	EndLine       int32                  `protobuf:"varint,7,opt,name=end_line,json=endLine,proto3" json:"end_line,omitempty"`
	Score         float32                `protobuf:"fixed32,8,opt,name=score,proto3" json:"score,omitempty"`
	Snippet       string                 `protobuf:"bytes,9,opt,name=snippet,proto3" json:"snippet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticHit) Reset() {
	*x = SemanticHit{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticHit) ProtoMessage() {}

func (x *SemanticHit) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticHit.ProtoReflect.Descriptor instead.
func (*SemanticHit) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{10}
}

func (x *SemanticHit) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *SemanticHit) GetRepoPath() string {
	if x != nil {
		return x.RepoPath
	}
	return ""
}

func (x *SemanticHit) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *SemanticHit) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *SemanticHit) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SemanticHit) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *SemanticHit) GetEndLine() int32 {
	if x != nil {
		return x.EndLine
	}
	return 0
}

func (x *SemanticHit) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SemanticHit) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{11}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{12}
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{13}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_internal_daemon_proto_search_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_daemon_proto_search_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_internal_daemon_proto_search_proto_rawDescGZIP(), []int{14}
}

var File_internal_daemon_proto_search_proto protoreflect.FileDescriptor

const file_internal_daemon_proto_search_proto_rawDesc = "" +
	"\n" +
	"\"internal/daemon/proto/search.proto\x12\x06daemon\"\x85\x03\n" +
	"\rSearchRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x1f\n" +
	"\vrepo_filter\x18\x02 \x01(\tR\n" +
	"repoFilter\x12\x1f\n" +
	"\vfile_filter\x18\x03 \x01(\tR\n" +
	"fileFilter\x12\x12\n" +
	"\x04lang\x18\x04 \x01(\tR\x04lang\x12%\n" +
	"\x0ecase_sensitive\x18\x05 \x01(\bR\rcaseSensitive\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12#\n" +
	"\rcontext_lines\x18\a \x01(\x05R\fcontextLines\x12\x1f\n" +
	"\voutput_mode\x18\b \x01(\tR\n" +
	"outputMode\x12C\n" +
	"\n" +
	"repo_names\x18\t \x03(\v2$.daemon.SearchRequest.RepoNamesEntryR\trepoNames\x1a<\n" +
	"\x0eRepoNamesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x0eSearchResponse\x12'\n" +
	"\amatches\x18\x01 \x03(\v2\r.daemon.MatchR\amatches\"\xba\x01\n" +
	"\x05Match\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1b\n" +
	"\trepo_path\x18\x02 \x01(\tR\brepoPath\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\x12\x12\n" +
	"\x04text\x18\x06 \x01(\tR\x04text\x12\x16\n" +
	"\x06before\x18\a \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\b \x01(\tR\x05after\"x\n" +
	"\fCountRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\x12\x1f\n" +
	"\vrepo_filter\x18\x02 \x01(\tR\n" +
	"repoFilter\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\x12\x19\n" +
	"\bgroup_by\x18\x04 \x01(\tR\agroupBy\"T\n" +
	"\rCountResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.daemon.CountResultR\aresults\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"9\n" +
	"\vCountResult\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"+\n" +
	"\x0fValidateRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\"j\n" +
	"\x10ValidateResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x16\n" +
	"\x06parsed\x18\x02 \x01(\tR\x06parsed\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x12\n" +
	"\x04hint\x18\x04 \x01(\tR\x04hint\"\x7f\n" +
	"\x15SemanticSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\x12\x14\n" +
	"\x05repos\x18\x03 \x03(\tR\x05repos\x12\x14\n" +
	"\x05langs\x18\x04 \x03(\tR\x05langs\x12\x16\n" +
	"\x06expand\x18\x05 \x01(\x05R\x06expand\"_\n" +
	"\x16SemanticSearchResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12'\n" +
	"\x04hits\x18\x02 \x03(\v2\x13.daemon.SemanticHitR\x04hits\"\xe4\x01\n" +
	"\vSemanticHit\x12\x12\n" +
	"\x04repo\x18\x01 \x01(\tR\x04repo\x12\x1b\n" +
	"\trepo_path\x18\x02 \x01(\tR\brepoPath\x12\x12\n" +
	"\x04file\x18\x03 \x01(\tR\x04file\x12\x12\n" +
	"\x04lang\x18\x04 \x01(\tR\x04lang\x12\x12\n" +
	"\x04kind\x18\x05 \x01(\tR\x04kind\x12\x1d\n" +
	"\n" +
	"start_line\x18\x06 \x01(\x05R\tstartLine\x12\x19\n" +
	"\bend_line\x18\a \x01(\x05R\aendLine\x12\x14\n" +
	"\x05score\x18\b \x01(\x02R\x05score\x12\x18\n" +
	"\asnippet\x18\t \x01(\tR\asnippet\"\r\n" +
	"\vPingRequest\"\x0e\n" +
	"\fPingResponse\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse2\xff\x02\n" +
	"\fSearchDaemon\x127\n" +
	"\x06Search\x12\x15.daemon.SearchRequest\x1a\x16.daemon.SearchResponse\x124\n" +
	"\x05Count\x12\x14.daemon.CountRequest\x1a\x15.daemon.CountResponse\x12=\n" +
	"\bValidate\x12\x17.daemon.ValidateRequest\x1a\x18.daemon.ValidateResponse\x121\n" +
	"\x04Ping\x12\x13.daemon.PingRequest\x1a\x14.daemon.PingResponse\x12=\n" +
	"\bShutdown\x12\x17.daemon.ShutdownRequest\x1a\x18.daemon.ShutdownResponse\x12O\n" +
	"\x0eSemanticSearch\x12\x1d.daemon.SemanticSearchRequest\x1a\x1e.daemon.SemanticSearchResponseB>Z<github.com/mad01/thismoon/services/csl/internal/daemon/protob\x06proto3"

var (
	file_internal_daemon_proto_search_proto_rawDescOnce sync.Once
	file_internal_daemon_proto_search_proto_rawDescData []byte
)

func file_internal_daemon_proto_search_proto_rawDescGZIP() []byte {
	file_internal_daemon_proto_search_proto_rawDescOnce.Do(func() {
		file_internal_daemon_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_daemon_proto_search_proto_rawDesc), len(file_internal_daemon_proto_search_proto_rawDesc)))
	})
	return file_internal_daemon_proto_search_proto_rawDescData
}

var file_internal_daemon_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_internal_daemon_proto_search_proto_goTypes = []any{
	(*SearchRequest)(nil),          // 0: daemon.SearchRequest
	(*SearchResponse)(nil),         // 1: daemon.SearchResponse
	(*Match)(nil),                  // 2: daemon.Match
	(*CountRequest)(nil),           // 3: daemon.CountRequest
	(*CountResponse)(nil),          // 4: daemon.CountResponse
	(*CountResult)(nil),            // 5: daemon.CountResult
	(*ValidateRequest)(nil),        // 6: daemon.ValidateRequest
	(*ValidateResponse)(nil),       // 7: daemon.ValidateResponse
	(*SemanticSearchRequest)(nil),  // 8: daemon.SemanticSearchRequest
	(*SemanticSearchResponse)(nil), // 9: daemon.SemanticSearchResponse
	(*SemanticHit)(nil),            // 10: daemon.SemanticHit
	(*PingRequest)(nil),            // 11: daemon.PingRequest
	(*PingResponse)(nil),           // 12: daemon.PingResponse
	(*ShutdownRequest)(nil),        // 13: daemon.ShutdownRequest
	(*ShutdownResponse)(nil),       // 14: daemon.ShutdownResponse
	nil,                            // 15: daemon.SearchRequest.RepoNamesEntry
}
var file_internal_daemon_proto_search_proto_depIdxs = []int32{
	15, // 0: daemon.SearchRequest.repo_names:type_name -> daemon.SearchRequest.RepoNamesEntry
	2,  // 1: daemon.SearchResponse.matches:type_name -> daemon.Match
	5,  // 2: daemon.CountResponse.results:type_name -> daemon.CountResult
	10, // 3: daemon.SemanticSearchResponse.hits:type_name -> daemon.SemanticHit
	0,  // 4: daemon.SearchDaemon.Search:input_type -> daemon.SearchRequest
	3,  // 5: daemon.SearchDaemon.Count:input_type -> daemon.CountRequest
	6,  // 6: daemon.SearchDaemon.Validate:input_type -> daemon.ValidateRequest
	11, // 7: daemon.SearchDaemon.Ping:input_type -> daemon.PingRequest
	13, // 8: daemon.SearchDaemon.Shutdown:input_type -> daemon.ShutdownRequest
	8,  // 9: daemon.SearchDaemon.SemanticSearch:input_type -> daemon.SemanticSearchRequest
	1,  // 10: daemon.SearchDaemon.Search:output_type -> daemon.SearchResponse
	4,  // 11: daemon.SearchDaemon.Count:output_type -> daemon.CountResponse
	7,  // 12: daemon.SearchDaemon.Validate:output_type -> daemon.ValidateResponse
	12, // 13: daemon.SearchDaemon.Ping:output_type -> daemon.PingResponse
	14, // 14: daemon.SearchDaemon.Shutdown:output_type -> daemon.ShutdownResponse
	9,  // 15: daemon.SearchDaemon.SemanticSearch:output_type -> daemon.SemanticSearchResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_daemon_proto_search_proto_init() }
func file_internal_daemon_proto_search_proto_init() {
	if File_internal_daemon_proto_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_daemon_proto_search_proto_rawDesc), len(file_internal_daemon_proto_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_daemon_proto_search_proto_goTypes,
		DependencyIndexes: file_internal_daemon_proto_search_proto_depIdxs,
		MessageInfos:      file_internal_daemon_proto_search_proto_msgTypes,
	}.Build()
	File_internal_daemon_proto_search_proto = out.File
	file_internal_daemon_proto_search_proto_goTypes = nil
	file_internal_daemon_proto_search_proto_depIdxs = nil
}
